### PR TITLE
Fix compiling with OSL 1.11.8

### LINKED ISSUE #2892: openimagedenoise:1.2.3 support
Can't build against `openimagedenoise:1.2.3`
Error log:
```
[  6%] Generating ../../../sandbox/shaders/max/as_max_color_balance.oso
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_chromatic_adaptation.h:177: error: function 'inverse' was not declared in this scope
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_chromatic_adaptation.h:177: error: No matching function call to 'inverse (matrix)'
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_chromatic_adaptation.h:177: error: Not allowed: 'unknown * matrix'
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_chromatic_adaptation.h:178: error: Not allowed: 'unknown * matrix'
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_chromatic_adaptation.h:177: error: Cannot assign matrix chromatic_adaptation_matrix = unknown
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_color_transforms.h:554: error: function 'inverse' was not declared in this scope
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_color_transforms.h:550: error: No matching function call to 'inverse (matrix)'
/build/appleseed-git/src/appleseed-git/src/appleseed.shaders/include/appleseed/color/as_color_transforms.h:550: error: Cannot assign matrix invXYZ = unknown
FAILED /build/appleseed-git/src/appleseed-git/src/appleseed.shaders/src/max/as_max_color_balance.osl
```
[full_log.txt](https://github.com/appleseedhq/appleseed/files/5252460/log.txt)

### PR DESCRIPTION
**Pull request by theartful**
Fixes #2892

### CODE REVIEW

File: src/appleseed.shaders/CMakeLists.txt [hunk 1]
```diff
@@ -403,6 +403,7 @@ foreach (osl_source ${osl_sources})
         OUTPUT ${oso_dir}/${oso_filename}
         COMMAND ${CMAKE_COMMAND} -E make_directory ${oso_dir}
         COMMAND ${PROJECT_SOURCE_DIR}/sandbox/bin/oslc ${OSLC_OPTIONS}
+            -I"${PROJECT_SOURCE_DIR}/sandbox/shaders/"
```
Comment (theartful) [inline src/appleseed.shaders/CMakeLists.txt:406]: OSL 1.11.7 and 1.11.8 changed where `stdosl.h` is stored (PREFIX/share/shaders instead of ../shaders), and its location is stored as a compile time constant as an absolute path (not relative).
However, if `stdosl.h` found in the includes it takes precedence.
These changes were introduced in https://github.com/imageworks/OpenShadingLanguage/pull/956 and the relevant change can be seen here:
https://github.com/imageworks/OpenShadingLanguage/blob/8ff28a0e062c714b74244cc89fd55461421c5a97/src/liboslcomp/oslcomp.cpp#L334-L341

File: src/appleseed/foundation/platform/python.h [hunk 2]
```diff
@@ -38,10 +38,23 @@
     #undef copysign
 #endif
 
+// wrap_python.hpp undefines _DEBUG and then redefines it, losing its value of 1
+// In OSL 1.11.8 osl/platform.h header assumes that _DEBUG=1, otherwise the
+// header can't be compiled
+#ifdef _DEBUG
+  #define _OLD_DEBUG _DEBUG
+#endif
```
Comment (theartful) [inline src/appleseed/foundation/platform/python.h:46]: wrap_python undefines _DEBUG and then redefines it, which makes it lose its value of 1. This value is used in osl/platform.h here
https://github.com/imageworks/OpenShadingLanguage/blob/8ff28a0e062c714b74244cc89fd55461421c5a97/src/include/OSL/platform.h#L229-L232
where OSL_DEBUG = _DEBUG as of here
https://github.com/imageworks/OpenShadingLanguage/blob/8ff28a0e062c714b74244cc89fd55461421c5a97/src/include/OSL/platform.h#L220-L222

File: src/appleseed/foundation/platform/python.h [hunk 3]
```diff
@@ -42,6 +42,14 @@
 #include "boost/python/detail/wrap_python.hpp"  // has to be first, to avoid redefinition warnings
 #include "boost/python.hpp"
 
+// wrap_python.hpp undefines _DEBUG and then redefines it without assigning it value of 1
+// In OSL 1.11.8 osl/platform.h header uses the syntax "#if _DEBUG" which assumes
+// that _DEBUG is not an empty macro, otherwise the header can't be compiled
+#ifdef _DEBUG
+  #undef _DEBUG
+  #define _DEBUG 1
+#endif
```
Comment (oktomus) [inline src/appleseed/foundation/platform/python.h:51]: So there is a conflit between boost and OSL ?

Why putting this here exactly ? There isn't any OSL include bellow those lines.

**Review by oktomus — COMMENTED** [review]
Thanks for the fix @theartful !

File: src/appleseed/foundation/platform/python.h (hunk 3 above)
Comment (theartful) [reply src/appleseed/foundation/platform/python.h:51]: Yes. `wrap_python.hpp` undefines "_DEBUG" then redefines it as an empty macro.
https://github.com/boostorg/python/blob/f1320bf30b4887aff28b9fc67b98f6f8be8c3684/include/boost/python/detail/wrap_python.hpp#L45
https://github.com/boostorg/python/blob/f1320bf30b4887aff28b9fc67b98f6f8be8c3684/include/boost/python/detail/wrap_python.hpp#L209

I added this here directly after "wrap_python.hpp" to fix the macro definition.
Personally I think that the syntax `#if OSL_DEBUG` instead of `#ifdef OSL_DEBUG` used in OSL is suboptimal.

Comment (oktomus) [reply src/appleseed/foundation/platform/python.h:51]: I see. We have some headers in appleseed wich goal is to include another header and then fix some things, like you are doing here. This ensure that the fix will be avilable everywhere we need `wrap_python` without having to write the fix multiple times.

@dictoon Can you confirm this ? Do you have an example in mind ?

**Comment by bartoszek** [comment]
Confirmed 👍 Work on ArchLinux against `openshadinglanguage:1.11.10.0`
`build_env={gcc:10.2.0, python2:2.7.18, python:3.9.0, embree:3.12.1, qt5:5.15.2, seexpr:2.11, boost:1.74.0, openexr:2.5.3, opencolorio:1.1.1, openimageio:2.2.9.0, openshadinglanguage:1.11.10.0}`
